name = "itsfrank/frktest"
version = "0.0.3"
description = "A basic test framework for Lune"
authors = ["Francis O'Brien (github.com/itsfrank)"]
repository = "https://github.com/itsfrank/frktest"
license = "MIT"

includes = [
	"pesde.toml",
	"README.md",
	"LICENSE",
	"src",
	".luaurc",
]

[target]
environment = "luau"
lib = "src/entrypoint.luau"

[indices]
default = "https://github.com/pesde-pkg/index"
